version: '3.4'

services:
  races.registration:
    image: races.registration
    build:
      context: .
      dockerfile: Registration/Races.Registration/Dockerfile
  races.management:
    image: races.management
    build:
      context: .
      dockerfile: Registration/Races.Management/Dockerfile
  mssqlserver:
    image: "microsoft/mssql-server-linux"
