version: '3.4'

services:
  races.registration:
    environment:
      - ASPNETCORE_ENVIRONMENT: Development
      - CONNECTIONSTRINGS__DEFAULTCONNECTION: "Server=tcp:localhost,6106;User ID=sa;Password=Your_password123;MultipleActiveResultSets=False;"
    ports:
      - "80"
  mssqlserver:
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "6106:1433"